apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: longhorn-system
spec:
  basicAuth:
    secret: authsecret
---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: longhorn-system
data:
  users: |2
    ZWJvbmQ6JGFwcjEkeWhWTW9icWckNkhYL3lnU1U1RExJQ1dteWxmVGR5LgoK
