---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`longhorn.cdc.com`)
    middlewares:
      - name: basic-auth
    services:
    - kind: Service
      name: longhorn-frontend
      namespace: longhorn-system
      port: 80
      responseForwarding:
        flushInterval: 1ms
      scheme: http
