repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-added-large-files
        args:
          - --maxkb=1024
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.2
    hooks:
      - id: terraform_fmt
        args:
          - --hook-config=--parallelism-ci-cpu-cores=2
      - id: terraform_validate
        args:
          - --hook-config=--parallelism-ci-cpu-cores=2
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --hook-config=--parallelism-ci-cpu-cores=2
      - id: terraform_trivy
        files: ^examples/
        args:
          - --args=--format=json
          - --args=--skip-dirs="**/.terraform"
