formatter: "markdown"
version: ">=0.17.0"

recursive:
  enabled: false
  path: modules

content: |-
  {{ .Header }}
  {{ .Footer }}
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

settings:
  # 为元素生成 HTML 锚标记。
  anchor: true
  # 在终端中打印结果的彩色版本。
  color: true
  # 将“默认”值显示为列（以表格格式）或部分（以文档格式）
  default: true
  description: false
  escape: true
  # 隐藏空白部分、比如 modules没有引用
  hide-empty: true
  html: true
  indent: 2
  # 如果.terraform.lock.hcl未在存储库中检查，则运行 terraform-docs 可能会在每次执行时生成不同的提供程序版本
  # 为了防止这种情况，您可以通过以下方式禁用它
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

sort:
  enabled: true
  by: name

sections:
  hide: []
  show: []

  hide-all: false
  show-all: true
