apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: ${namespace}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`${access_url}`)
      kind: Rule
      services:
      - name: api@internal
        kind: TraefikService
